//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int id { get; set; }
        public string userName { get; set; }
        public string displayName { get; set; }
        public string password { get; set; }
        public int roleId { get; set; }
    
        public virtual AccountRole AccountRole { get; set; }
    }
}
