//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.ExportInfoes = new HashSet<ExportInfo>();
            this.ImportInfoes = new HashSet<ImportInfo>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public int unitId { get; set; }
        public int supplierId { get; set; }
        public string qrCode { get; set; }
        public string barcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExportInfo> ExportInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportInfo> ImportInfoes { get; set; }
        public virtual MeasuringUnit MeasuringUnit { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
